// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlI7IRtrUXt1s6R-W4RLFSr6FozhsMng',
    appId: '1:683852157796:web:995d471fbea5577ea0e071',
    messagingSenderId: '683852157796',
    projectId: 'my-su-project',
    authDomain: 'my-su-project.firebaseapp.com',
    storageBucket: 'my-su-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPpSHeStB8lFi5n2GHTd5TnKXOhr116Q',
    appId: '1:683852157796:android:d3a219d85b26e737a0e071',
    messagingSenderId: '683852157796',
    projectId: 'my-su-project',
    storageBucket: 'my-su-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTWqL7YmHElh7wX1Fh3St_xLmLEyc-Ak',
    appId: '1:683852157796:ios:04953de7585d3313a0e071',
    messagingSenderId: '683852157796',
    projectId: 'my-su-project',
    storageBucket: 'my-su-project.appspot.com',
    iosClientId: '683852157796-e74tplclp29s8841lpeu34dp189hmid1.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpTWqL7YmHElh7wX1Fh3St_xLmLEyc-Ak',
    appId: '1:683852157796:ios:04953de7585d3313a0e071',
    messagingSenderId: '683852157796',
    projectId: 'my-su-project',
    storageBucket: 'my-su-project.appspot.com',
    iosClientId: '683852157796-e74tplclp29s8841lpeu34dp189hmid1.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryapp',
  );
}
